# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_designe_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 850, 151))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 160, 840, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(10, 230, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("background-color: rgb(0, 172, 138);\n"
"border: 2px solid black;")
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(305, 230, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"border: 2px solid black;")
        self.delete_button.setObjectName("delete_button")
        self.check_list_button = QtWidgets.QPushButton(self.centralwidget)
        self.check_list_button.setGeometry(QtCore.QRect(610, 230, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.check_list_button.setFont(font)
        self.check_list_button.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"border: 2px solid black;")
        self.check_list_button.setObjectName("check_list_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TC Data Modification"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Для добавления/удаления данных из базы данных впишите в поле снизу нужную информацию<br/>в формате: номер_транспортного_средства фамилия имя отвество.</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Пример: А777ББ666 Иванов Иван Иванович.<br/></span><span style=\" font-size:14pt; color:#aa0000;\">Вносите данные с начала строки соблюдая все пробелы.<br/>Буквы в номере могут быть только: А, В, Е, К, М, Н, О, Р, С, Т, У, Х.</span><span style=\" font-size:14pt;\"><br/></span></p></body></html>"))
        self.add_button.setText(_translate("MainWindow", "Добавить"))
        self.delete_button.setText(_translate("MainWindow", "Удалить"))
        self.check_list_button.setText(_translate("MainWindow", "Посмотреть список"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
