# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_designe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 480)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("border-color: rgb(15, 15, 15), 2px solid black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-color: rgb(15, 15, 15), 2px solid black;")
        self.centralwidget.setObjectName("centralwidget")
        self.camera_header = QtWidgets.QLabel(self.centralwidget)
        self.camera_header.setEnabled(True)
        self.camera_header.setGeometry(QtCore.QRect(20, 20, 551, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.camera_header.setFont(font)
        self.camera_header.setAutoFillBackground(False)
        self.camera_header.setStyleSheet("background-color: rgb(0, 172, 138);\n"
"border: 2px solid black;")
        self.camera_header.setLineWidth(1)
        self.camera_header.setObjectName("camera_header")
        self.log_header = QtWidgets.QLabel(self.centralwidget)
        self.log_header.setEnabled(True)
        self.log_header.setGeometry(QtCore.QRect(630, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.log_header.setFont(font)
        self.log_header.setAutoFillBackground(False)
        self.log_header.setStyleSheet("background-color: rgb(0, 172, 138);\n"
"border: 2px solid black;")
        self.log_header.setLineWidth(1)
        self.log_header.setObjectName("log_header")
        self.log_text = QtWidgets.QTextEdit(self.centralwidget)
        self.log_text.setGeometry(QtCore.QRect(630, 60, 281, 311))
        self.log_text.setStyleSheet("border: 2px solid black;")
        self.log_text.setObjectName("log_text")
        self.video_label = QtWidgets.QLabel(self.centralwidget)
        self.video_label.setEnabled(True)
        self.video_label.setGeometry(QtCore.QRect(20, 60, 551, 311))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.video_label.setFont(font)
        self.video_label.setAutoFillBackground(False)
        self.video_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;")
        self.video_label.setLineWidth(1)
        self.video_label.setText("")
        self.video_label.setObjectName("video_label")
        self.check_button = QtWidgets.QPushButton(self.centralwidget)
        self.check_button.setGeometry(QtCore.QRect(20, 400, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.check_button.setFont(font)
        self.check_button.setStyleSheet("background-color: rgb(0, 172, 138);\n"
"border: 2px solid black;")
        self.check_button.setObjectName("check_button")
        self.database_button = QtWidgets.QPushButton(self.centralwidget)
        self.database_button.setGeometry(QtCore.QRect(330, 400, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.database_button.setFont(font)
        self.database_button.setStyleSheet("background-color: rgb(0, 172, 138);\n"
"border: 2px solid black;")
        self.database_button.setObjectName("database_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TC - Traffic Control"))
        self.camera_header.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.camera_header.setText(_translate("MainWindow", "Камера"))
        self.log_header.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.log_header.setText(_translate("MainWindow", "Логи"))
        self.video_label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.check_button.setText(_translate("MainWindow", "Запросить проверку"))
        self.database_button.setText(_translate("MainWindow", "Внести изменения в БД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
